// metadata.js
export const Metadata = {
  title: "Protek",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/logo/logo.png"],
    apple: ["/images/logo/logo.png"],
    shortcut: ["/images/logo/logo.png"],
  },
  };
  
